# Generated by Django 3.1.7 on 2021-05-30 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pavilion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_TC', models.CharField(max_length=255)),
                ('number_pavilion', models.CharField(max_length=3, verbose_name='номер павилиона')),
                ('floor', models.SmallIntegerField(verbose_name='этаж')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('area', models.SmallIntegerField(verbose_name='общая площадь')),
                ('cost_sqm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='стоимость за кв.м')),
                ('add_value_rito', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='кооф. добавочной стоимотси')),
            ],
            options={
                'verbose_name': 'Павильон',
                'verbose_name_plural': 'Павильоны',
            },
        ),
        migrations.CreateModel(
            name='TC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название ТЦ')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('count_pavilions', models.SmallIntegerField()),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость')),
                ('add_value_rito', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='кооф. добавочной стоимотси')),
                ('storeys', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'ТЦ',
                'verbose_name_plural': 'ТЦы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_phone', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('role', models.CharField(max_length=255, verbose_name='роль')),
                ('phone', models.CharField(max_length=255, verbose_name='телефон')),
                ('gender', models.CharField(max_length=255, verbose_name='пол')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_TC', models.CharField(max_length=255, verbose_name='название тц')),
                ('number_pavilion', models.CharField(max_length=3, verbose_name='номер павилиона ')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('start_rent', models.DateField(verbose_name='начало ренты')),
                ('finish_rent', models.DateField(verbose_name='окончание ренты')),
                ('ID_Worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.worker')),
                ('ID_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.tenant')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
